/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/categories/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get category strength scores
         * @description Returns the average decayed score per category for the authenticated user. Strength is a 0–100 value representing current mastery. Categories with no problems are omitted.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Per-category strength scores */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.categoryStatsResponse"][];
                    };
                };
                /** @description Missing or invalid JWT token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.errorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.errorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/weakest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get weakest category with recommendations
         * @description Identifies the category with the lowest average decayed score and returns 3 curated LeetCode problems to practice. Used to drive the dashboard weakness banner.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Weakest category with 3 recommended problems */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.weakestResponse"];
                    };
                };
                /** @description Missing or invalid JWT token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.errorResponse"];
                    };
                };
                /** @description No problems logged yet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.errorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.errorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List logged problems with filtering and pagination
         * @description Returns a paginated, filtered list of problems for the authenticated user, always sorted by created_at DESC. Supports name search, date range, category/difficulty/score filters, and offset-based pagination.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Name search (case-insensitive partial match) */
                    q?: string;
                    /** @description Category filter (repeatable; matches any) */
                    category?: string[];
                    /** @description Difficulty filter (repeatable: easy|medium|hard) */
                    difficulty?: string[];
                    /** @description Minimum raw score (inclusive) */
                    score_min?: number;
                    /** @description Maximum raw score (inclusive) */
                    score_max?: number;
                    /** @description Solved-on start date YYYY-MM-DD (inclusive) */
                    from?: string;
                    /** @description Solved-on end date YYYY-MM-DD (inclusive) */
                    to?: string;
                    /** @description Page size (default 20) */
                    limit?: number;
                    /** @description Record offset (default 0) */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated problem list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.listProblemsResponse"];
                    };
                };
                /** @description Missing or invalid JWT token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.errorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.errorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Log a new problem attempt
         * @description Records a LeetCode problem attempt and computes a score. Score formula: base 100, -10 per extra attempt (capped -40), -25 if solution viewed, floor 5. Decay applies at read time: 3-day grace period, then -2pts/day, floor at 30% of raw score.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Problem attempt details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handlers.logProblemRequest"];
                };
            };
            responses: {
                /** @description Created problem with computed score */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.problemResponse"];
                    };
                };
                /** @description Invalid input — bad category, difficulty, or missing name */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.errorResponse"];
                    };
                };
                /** @description Missing or invalid JWT token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.errorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.errorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "handlers.categoryStatsResponse": {
            category?: string;
            problem_count?: number;
            strength?: number;
        };
        "handlers.errorResponse": {
            error?: string;
        };
        "handlers.listProblemsResponse": {
            limit?: number;
            offset?: number;
            problems?: components["schemas"]["handlers.problemResponse"][];
            total?: number;
        };
        "handlers.logProblemRequest": {
            attempts?: number;
            categories?: string[];
            difficulty?: string;
            looked_at_solution?: boolean;
            name?: string;
            /**
             * @description SolutionType indicates how the user solved the problem.
             *     Accepted values: "none" (default), "brute_force", "optimal".
             *     "brute_force" applies a -15 point penalty; the others carry no penalty.
             */
            solution_type?: string;
            time_taken_mins?: number;
        };
        "handlers.problemResponse": {
            attempts?: number;
            categories?: string[];
            created_at?: string;
            decayed_score?: number;
            difficulty?: string;
            id?: number;
            looked_at_solution?: boolean;
            name?: string;
            score?: number;
            solution_type?: string;
            solved_at?: string;
            time_taken_mins?: number;
        };
        "handlers.weakestResponse": {
            category?: string;
            recommendations?: string[];
            strength?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
