// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the average decayed score per category for the authenticated user. Strength is a 0–100 value representing current mastery. Categories with no problems are omitted.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Get category strength scores",
                "responses": {
                    "200": {
                        "description": "Per-category strength scores",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.categoryStatsResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/categories/weakest": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Identifies the category with the lowest average decayed score and returns 3 curated LeetCode problems to practice. Used to drive the dashboard weakness banner.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Get weakest category with recommendations",
                "responses": {
                    "200": {
                        "description": "Weakest category with 3 recommended problems",
                        "schema": {
                            "$ref": "#/definitions/handlers.weakestResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "No problems logged yet",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/problems": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated, filtered list of problems for the authenticated user, always sorted by created_at DESC. Supports name search, date range, category/difficulty/score filters, and offset-based pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "problems"
                ],
                "summary": "List logged problems with filtering and pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name search (case-insensitive partial match)",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Category filter (repeatable; matches any)",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Difficulty filter (repeatable: easy|medium|hard)",
                        "name": "difficulty",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum raw score (inclusive)",
                        "name": "score_min",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum raw score (inclusive)",
                        "name": "score_max",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Solved-on start date YYYY-MM-DD (inclusive)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Solved-on end date YYYY-MM-DD (inclusive)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Record offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated problem list",
                        "schema": {
                            "$ref": "#/definitions/handlers.listProblemsResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Records a LeetCode problem attempt and computes a score. Score formula: base 100, -10 per extra attempt (capped -40), -25 if solution viewed, floor 5. Decay applies at read time: 3-day grace period, then -2pts/day, floor at 30% of raw score.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "problems"
                ],
                "summary": "Log a new problem attempt",
                "parameters": [
                    {
                        "description": "Problem attempt details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.logProblemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created problem with computed score",
                        "schema": {
                            "$ref": "#/definitions/handlers.problemResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input — bad category, difficulty, or missing name",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT token",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.categoryStatsResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "problem_count": {
                    "type": "integer"
                },
                "strength": {
                    "type": "number"
                }
            }
        },
        "handlers.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handlers.listProblemsResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "problems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.problemResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handlers.logProblemRequest": {
            "type": "object",
            "properties": {
                "attempts": {
                    "type": "integer"
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "difficulty": {
                    "type": "string"
                },
                "looked_at_solution": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "solution_type": {
                    "description": "SolutionType indicates how the user solved the problem.\nAccepted values: \"none\" (default), \"brute_force\", \"optimal\".\n\"brute_force\" applies a -15 point penalty; the others carry no penalty.",
                    "type": "string"
                },
                "time_taken_mins": {
                    "type": "integer"
                }
            }
        },
        "handlers.problemResponse": {
            "type": "object",
            "properties": {
                "attempts": {
                    "type": "integer"
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "decayed_score": {
                    "type": "number"
                },
                "difficulty": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "looked_at_solution": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "solution_type": {
                    "type": "string"
                },
                "solved_at": {
                    "type": "string"
                },
                "time_taken_mins": {
                    "type": "integer"
                }
            }
        },
        "handlers.weakestResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "strength": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter your Clerk session token as: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Interview Skill Radar API",
	Description:      "Backend API for tracking LeetCode problem attempts, computing skill scores with time decay, and surfacing category weaknesses.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
